# Generated by Django 2.0.3 on 2019-06-09 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import watcher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('eventImage', models.ImageField(upload_to='')),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=watcher.models.get_image_filename, verbose_name='Image')),
                ('foodName', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=99)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact', models.BooleanField(default=False, help_text='가맹점일 경우 체크하시오.')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice', models.TextField(blank=True)),
                ('spec', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('seatImage', models.ImageField(blank=True, upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.Room')),
            ],
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.Room'),
        ),
        migrations.AddField(
            model_name='coment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.Room'),
        ),
    ]
