# Generated by Django 2.0.3 on 2019-06-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='star',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coment',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
